#!/bin/bash
echo ----------------------------
echo Tide publisher
echo ----------------------------
#
export SCRIPT_DIR=`dirname $0`
echo moving to ${SCRIPT_DIR}
cd ${SCRIPT_DIR}
# export JAVA_HOME=/usr/java/jre1.6.0_17
# export PATH=$JAVA_HOME/bin:$PATH
#
export RADICAL=$1
echo Transforming ${RADICAL}.xml into ${RADICAL}.pdf
#
export OLIVSOFT_HOME=../..
#
export CP=$CP:../../build/libs/release-4.0.0.0-all.jar
export CP=${CP}:${OLIVSOFT_HOME}/all-3rd-party/orai18n-collation.jar
export CP=${CP}:${OLIVSOFT_HOME}/all-3rd-party/orai18n-mapping.jar
export CP=${CP}:${OLIVSOFT_HOME}/all-3rd-party/fnd2.zip
export CP=${CP}:${OLIVSOFT_HOME}/all-3rd-party/xdo-0301.jar
#
export XSL_STYLESHEET=./tide2fop.xsl
echo Publishing
java -Xms256m -Xmx1024m -classpath ${CP} oracle.apps.xdo.template.FOProcessor -xml ${RADICAL}.xml -xsl ${XSL_STYLESHEET} -pdf ${RADICAL}.pdf
echo Done transforming, displaying.
if [[ "$OSTYPE" == "darwin"* ]] # Mac
then
  open ${RADICAL}.pdf
else                            # Linux
  evince ${RADICAL}.pdf
fi
# exit
