#!/bin/bash
echo Parameters: $*
export SCRIPT_DIR=`dirname $0`
echo moving to ${SCRIPT_DIR}
cd ${SCRIPT_DIR}
# export JAVA_HOME=/usr/java/jre1.6.0_17
# export PATH=$JAVA_HOME/bin:$PATH
export OLIVSOFT_HOME=../..
#
CP=""
CP=$CP:../../build/libs/release-4.0.0.0-all.jar
CP=$CP:$OLIVSOFT_HOME/all-3rd-party/orai18n-collation.jar
CP=$CP:$OLIVSOFT_HOME/all-3rd-party/orai18n-mapping.jar
CP=$CP:$OLIVSOFT_HOME/all-3rd-party/fnd2.zip
CP=$CP:$OLIVSOFT_HOME/all-3rd-party/xdo-0301.jar
export CP
#
echo Processing PDF file
XSL_STYLESHEET=./lunar2fop.xsl
LANG=$1
if [ $LANG = "FR" ] 
then
  echo Will speak French
  PRM_OPTION="-docconf ./lang_fr.cfg" 
  cp literals_fr.xsl literals.xsl
else
  echo Will speak English
  cp literals_en.xsl literals.xsl
  set PRM_OPTION="-docconf ./lang_en.cfg"
fi
echo Publishing
java -Xms256m -Xmx1024m -classpath $CP oracle.apps.xdo.template.FOProcessor $PRM_OPTION -xml $2 -xsl $XSL_STYLESHEET -pdf $3
echo Done calculating, $3 is ready.
evince $3
# exit
